## Notebook Overview
## Single‑layer Exact Gaussian Process (GP) regression model
- This notebook implements a single‑layer Exact Gaussian Process (GP) regression model for predicting ISUP grades from radiomic features.
- It performs a **full hyperparameter grid search** over:
  - PCA dimensions  
  - Kernel types  
  - Learning rates  
  - Noise initializations  
- The grid search trains a total of 315 Gaussian Process models.  
- Each GP model is trained for 500 optimization iterations.  
- GPU acceleration is used to speed up training for each individual GP model.  
- Parallel execution across multiple GP models is not possible on a single GPU, because:
  - Exact GPs require large covariance matrices and Cholesky decompositions.  
  - These operations fully occupy GPU memory and compute resources.  
  - Running multiple GPs simultaneously would cause memory conflicts and numerical instability.  
- For this reason, GP models are trained sequentially on the GPU, ensuring stable and reliable execution.
- Evaluation part: 
     - The best model is selected by maximizing R² and minimizing mean predictive uncertainty.
     - For the best model, predictive standard deviations are grouped by the true ISUP grade.
     - Continuous regression outputs are rounded to the nearest integer (and clipped to 0–5) to compute classification metrics such as accuracy, macro‑F1, and the confusion matrix.


- Parts of the code were adapted and modified from the GPyTorch documentation: https://docs.gpytorch.ai/en/stable/examples/01_Exact_GPs/Simple_GP_Regression.html

In [1]:
import torch
import numpy as np
import gpytorch
import pandas as pd
import sys, os
sys.path.append(os.path.abspath(os.path.join(os.getcwd(), "../..")))

from tqdm import tqdm

from sklearn.metrics import accuracy_score, f1_score, confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from deep_gp.gptorch_example import ExactGPModel
from deep_gp.preprocessing_data import load_data, undersample_class0, apply_smote
from sklearn.metrics import mean_squared_error, r2_score

%matplotlib inline
%load_ext autoreload
%autoreload 2

In [2]:
# Use GPU if available
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Using device:", device)


Using device: cuda


In [3]:
# Load data
data = load_data()
df_new = undersample_class0(data)
df_resampled = apply_smote(df_new)

X_balanced = df_resampled.drop(columns=["case_ISUP"])
y_balanced = df_resampled["case_ISUP"]


In [4]:
# Split data
X_train, X_test, y_train, y_test = train_test_split(
    X_balanced, y_balanced, test_size=0.2, random_state=42
)

# Scale features
scaler_X = StandardScaler()
X_train_scaled = scaler_X.fit_transform(X_train)
X_test_scaled  = scaler_X.transform(X_test)

# Scale target
scaler_y = StandardScaler()
y_train_scaled = scaler_y.fit_transform(y_train.values.reshape(-1,1)).ravel()
y_test_scaled  = scaler_y.transform(y_test.values.reshape(-1,1)).ravel()


In [5]:
# Define hyperparameters
results = []
pca_components_list = [5, 10, 15, 20, 30, 40, 50]
kernels = ["matern_15", "matern_25", "rbf_ard"]
learning_rates = [0.05, 0.01, 0.001]
noise_values = ["learned", 0.01, 0.05, 0.1, 0.2]

# Total number of of GP models that will be trained.
num_models = (
    len(pca_components_list)
    * len(kernels)
    * len(learning_rates)
    * len(noise_values)
)

print(f"Total models to be tested: {num_models}")


Total models to be tested: 315


In [ ]:
# Hyperparameter search: PCA → GP training → prediction 
for n_comp in pca_components_list:
    print(f"\n PCA = {n_comp} components")

    # PCA transform
    pca = PCA(n_components=n_comp, random_state=42)
    X_train_pca = pca.fit_transform(X_train_scaled)
    X_test_pca  = pca.transform(X_test_scaled)

    # Move tensors to GPU
    X_train_tensor = torch.tensor(X_train_pca, dtype=torch.float32).to(device)
    X_test_tensor  = torch.tensor(X_test_pca,  dtype=torch.float32).to(device)

    y_train_tensor = torch.tensor(y_train_scaled, dtype=torch.float32).to(device)
    y_test_tensor  = torch.tensor(y_test_scaled,  dtype=torch.float32).to(device)

    for kernel in kernels:
        for lr in learning_rates:
            for noise_init in noise_values:

                print(f"\n--- Kernel: {kernel} | LR: {lr} | Noise: {noise_init} ---")

                torch.manual_seed(42)

                likelihood = gpytorch.likelihoods.GaussianLikelihood().to(device)

                if noise_init == "learned":
                    print("   Noise: learned (GPyTorch default, trainable)")
                else:
                    likelihood.noise = noise_init
                    print(f"   Noise init: {noise_init} (trainable)")

                model = ExactGPModel(
                    X_train_tensor, y_train_tensor, likelihood, kernel_type=kernel
                ).to(device)

                model.train()
                likelihood.train()

                optimizer = torch.optim.Adam(model.parameters(), lr=lr)
                mll = gpytorch.mlls.ExactMarginalLogLikelihood(likelihood, model)

                # tqdm progress bar for 500 iterations
                for i in tqdm(range(500), desc="Training GP", leave=False):
                    optimizer.zero_grad()
                    output = model(X_train_tensor)
                    loss = -mll(output, y_train_tensor)
                    loss.backward()
                    optimizer.step()

                # Predict
                model.eval()
                likelihood.eval()

                with torch.no_grad(), gpytorch.settings.fast_pred_var():
                    preds = likelihood(model(X_test_tensor))


                # Move predictions back to CPU
                mean_scaled = preds.mean.cpu().numpy()
                var_scaled  = preds.variance.cpu().numpy()
                std_scaled  = np.sqrt(var_scaled)

                # Back to ISUP scale
                mean = scaler_y.inverse_transform(mean_scaled.reshape(-1,1)).ravel()
                std  = std_scaled * scaler_y.scale_[0]
                y_test_original = y_test.values
               

                mse = mean_squared_error(y_test_original, mean)
                r2  = r2_score(y_test_original, mean)
                mean_unc = std.mean()

                print(f"MSE: {mse:.4f} | R²: {r2:.4f} | Mean Uncertainty: {mean_unc:.4f}")

                # Build uncertainty dataframe (for best-model analysis)
                df_unc = pd.DataFrame({
                    "true": y_test_original,
                    "pred": mean,
                    "std": std
                })

                results.append([
                n_comp, kernel, lr, noise_init, mse, r2, mean_unc, df_unc ])



 PCA = 5 components

--- Kernel: matern_15 | LR: 0.05 | Noise: learned ---
   Noise: learned (GPyTorch default, trainable)


MSE: 2.2500 | R²: 0.3176 | Mean Uncertainty: 1.5899

--- Kernel: matern_15 | LR: 0.05 | Noise: 0.01 ---
   Noise init: 0.01 (trainable)


MSE: 2.2519 | R²: 0.3171 | Mean Uncertainty: 1.5911

--- Kernel: matern_15 | LR: 0.05 | Noise: 0.05 ---
   Noise init: 0.05 (trainable)


MSE: 2.2503 | R²: 0.3175 | Mean Uncertainty: 1.5893

--- Kernel: matern_15 | LR: 0.05 | Noise: 0.1 ---
   Noise init: 0.1 (trainable)


MSE: 2.2504 | R²: 0.3175 | Mean Uncertainty: 1.5868

--- Kernel: matern_15 | LR: 0.05 | Noise: 0.2 ---
   Noise init: 0.2 (trainable)


MSE: 2.2486 | R²: 0.3181 | Mean Uncertainty: 1.5868

--- Kernel: matern_15 | LR: 0.01 | Noise: learned ---
   Noise: learned (GPyTorch default, trainable)


MSE: 2.2318 | R²: 0.3231 | Mean Uncertainty: 1.5880

--- Kernel: matern_15 | LR: 0.01 | Noise: 0.01 ---
   Noise init: 0.01 (trainable)


MSE: 2.2401 | R²: 0.3206 | Mean Uncertainty: 1.5777

--- Kernel: matern_15 | LR: 0.01 | Noise: 0.05 ---
   Noise init: 0.05 (trainable)


MSE: 2.2430 | R²: 0.3197 | Mean Uncertainty: 1.5759

--- Kernel: matern_15 | LR: 0.01 | Noise: 0.1 ---
   Noise init: 0.1 (trainable)


MSE: 2.2423 | R²: 0.3200 | Mean Uncertainty: 1.5776

--- Kernel: matern_15 | LR: 0.01 | Noise: 0.2 ---
   Noise init: 0.2 (trainable)


MSE: 2.2354 | R²: 0.3221 | Mean Uncertainty: 1.5775

--- Kernel: matern_15 | LR: 0.001 | Noise: learned ---
   Noise: learned (GPyTorch default, trainable)


MSE: 2.3396 | R²: 0.2904 | Mean Uncertainty: 1.7505

--- Kernel: matern_15 | LR: 0.001 | Noise: 0.01 ---
   Noise init: 0.01 (trainable)


MSE: 2.2524 | R²: 0.3169 | Mean Uncertainty: 1.5512

--- Kernel: matern_15 | LR: 0.001 | Noise: 0.05 ---
   Noise init: 0.05 (trainable)


MSE: 2.2508 | R²: 0.3174 | Mean Uncertainty: 1.5705

--- Kernel: matern_15 | LR: 0.001 | Noise: 0.1 ---
   Noise init: 0.1 (trainable)


MSE: 2.2445 | R²: 0.3193 | Mean Uncertainty: 1.5855

--- Kernel: matern_15 | LR: 0.001 | Noise: 0.2 ---
   Noise init: 0.2 (trainable)


MSE: 2.2386 | R²: 0.3211 | Mean Uncertainty: 1.6044

--- Kernel: matern_25 | LR: 0.05 | Noise: learned ---
   Noise: learned (GPyTorch default, trainable)


MSE: 2.3111 | R²: 0.2991 | Mean Uncertainty: 1.6120

--- Kernel: matern_25 | LR: 0.05 | Noise: 0.01 ---
   Noise init: 0.01 (trainable)


MSE: 2.3115 | R²: 0.2990 | Mean Uncertainty: 1.6087

--- Kernel: matern_25 | LR: 0.05 | Noise: 0.05 ---
   Noise init: 0.05 (trainable)


MSE: 2.3100 | R²: 0.2994 | Mean Uncertainty: 1.6075

--- Kernel: matern_25 | LR: 0.05 | Noise: 0.1 ---
   Noise init: 0.1 (trainable)


MSE: 2.3089 | R²: 0.2998 | Mean Uncertainty: 1.6002

--- Kernel: matern_25 | LR: 0.05 | Noise: 0.2 ---
   Noise init: 0.2 (trainable)


MSE: 2.3079 | R²: 0.3001 | Mean Uncertainty: 1.5986

--- Kernel: matern_25 | LR: 0.01 | Noise: learned ---
   Noise: learned (GPyTorch default, trainable)


MSE: 2.2859 | R²: 0.3067 | Mean Uncertainty: 1.5990

--- Kernel: matern_25 | LR: 0.01 | Noise: 0.01 ---
   Noise init: 0.01 (trainable)


MSE: 2.2958 | R²: 0.3037 | Mean Uncertainty: 1.5941

--- Kernel: matern_25 | LR: 0.01 | Noise: 0.05 ---
   Noise init: 0.05 (trainable)


MSE: 2.2928 | R²: 0.3047 | Mean Uncertainty: 1.5925

--- Kernel: matern_25 | LR: 0.01 | Noise: 0.1 ---
   Noise init: 0.1 (trainable)


MSE: 2.2953 | R²: 0.3039 | Mean Uncertainty: 1.5919

--- Kernel: matern_25 | LR: 0.01 | Noise: 0.2 ---
   Noise init: 0.2 (trainable)


MSE: 2.2934 | R²: 0.3045 | Mean Uncertainty: 1.5914

--- Kernel: matern_25 | LR: 0.001 | Noise: learned ---
   Noise: learned (GPyTorch default, trainable)


MSE: 2.3442 | R²: 0.2891 | Mean Uncertainty: 1.7479

--- Kernel: matern_25 | LR: 0.001 | Noise: 0.01 ---
   Noise init: 0.01 (trainable)


MSE: 2.3058 | R²: 0.3007 | Mean Uncertainty: 1.5606

--- Kernel: matern_25 | LR: 0.001 | Noise: 0.05 ---
   Noise init: 0.05 (trainable)


MSE: 2.3057 | R²: 0.3007 | Mean Uncertainty: 1.5794

--- Kernel: matern_25 | LR: 0.001 | Noise: 0.1 ---
   Noise init: 0.1 (trainable)


MSE: 2.2967 | R²: 0.3035 | Mean Uncertainty: 1.5934

--- Kernel: matern_25 | LR: 0.001 | Noise: 0.2 ---
   Noise init: 0.2 (trainable)


MSE: 2.2721 | R²: 0.3109 | Mean Uncertainty: 1.6113

--- Kernel: rbf_ard | LR: 0.05 | Noise: learned ---
   Noise: learned (GPyTorch default, trainable)


MSE: 2.4147 | R²: 0.2677 | Mean Uncertainty: 1.6434

--- Kernel: rbf_ard | LR: 0.05 | Noise: 0.01 ---
   Noise init: 0.01 (trainable)


MSE: 2.4156 | R²: 0.2674 | Mean Uncertainty: 1.6361

--- Kernel: rbf_ard | LR: 0.05 | Noise: 0.05 ---
   Noise init: 0.05 (trainable)


MSE: 2.4190 | R²: 0.2664 | Mean Uncertainty: 1.6396

--- Kernel: rbf_ard | LR: 0.05 | Noise: 0.1 ---
   Noise init: 0.1 (trainable)


MSE: 2.4173 | R²: 0.2669 | Mean Uncertainty: 1.6367

--- Kernel: rbf_ard | LR: 0.05 | Noise: 0.2 ---
   Noise init: 0.2 (trainable)


MSE: 2.4158 | R²: 0.2673 | Mean Uncertainty: 1.6346

--- Kernel: rbf_ard | LR: 0.01 | Noise: learned ---
   Noise: learned (GPyTorch default, trainable)


MSE: 2.4056 | R²: 0.2704 | Mean Uncertainty: 1.6221

--- Kernel: rbf_ard | LR: 0.01 | Noise: 0.01 ---
   Noise init: 0.01 (trainable)


MSE: 2.4150 | R²: 0.2676 | Mean Uncertainty: 1.6209

--- Kernel: rbf_ard | LR: 0.01 | Noise: 0.05 ---
   Noise init: 0.05 (trainable)


MSE: 2.4149 | R²: 0.2676 | Mean Uncertainty: 1.6216

--- Kernel: rbf_ard | LR: 0.01 | Noise: 0.1 ---
   Noise init: 0.1 (trainable)


MSE: 2.4124 | R²: 0.2684 | Mean Uncertainty: 1.6186

--- Kernel: rbf_ard | LR: 0.01 | Noise: 0.2 ---
   Noise init: 0.2 (trainable)


MSE: 2.4113 | R²: 0.2687 | Mean Uncertainty: 1.6178

--- Kernel: rbf_ard | LR: 0.001 | Noise: learned ---
   Noise: learned (GPyTorch default, trainable)


MSE: 2.3624 | R²: 0.2835 | Mean Uncertainty: 1.7439

--- Kernel: rbf_ard | LR: 0.001 | Noise: 0.01 ---
   Noise init: 0.01 (trainable)


MSE: 2.4126 | R²: 0.2683 | Mean Uncertainty: 1.5727

--- Kernel: rbf_ard | LR: 0.001 | Noise: 0.05 ---
   Noise init: 0.05 (trainable)


MSE: 2.4184 | R²: 0.2665 | Mean Uncertainty: 1.5926

--- Kernel: rbf_ard | LR: 0.001 | Noise: 0.1 ---
   Noise init: 0.1 (trainable)


MSE: 2.4124 | R²: 0.2684 | Mean Uncertainty: 1.6135

--- Kernel: rbf_ard | LR: 0.001 | Noise: 0.2 ---
   Noise init: 0.2 (trainable)


MSE: 2.3882 | R²: 0.2757 | Mean Uncertainty: 1.6288

 PCA = 10 components

--- Kernel: matern_15 | LR: 0.05 | Noise: learned ---
   Noise: learned (GPyTorch default, trainable)


MSE: 1.7343 | R²: 0.4740 | Mean Uncertainty: 1.3963

--- Kernel: matern_15 | LR: 0.05 | Noise: 0.01 ---
   Noise init: 0.01 (trainable)


MSE: 1.7289 | R²: 0.4757 | Mean Uncertainty: 1.3983

--- Kernel: matern_15 | LR: 0.05 | Noise: 0.05 ---
   Noise init: 0.05 (trainable)


MSE: 1.7307 | R²: 0.4751 | Mean Uncertainty: 1.3945

--- Kernel: matern_15 | LR: 0.05 | Noise: 0.1 ---
   Noise init: 0.1 (trainable)


MSE: 1.7334 | R²: 0.4743 | Mean Uncertainty: 1.3959

--- Kernel: matern_15 | LR: 0.05 | Noise: 0.2 ---
   Noise init: 0.2 (trainable)


MSE: 1.7334 | R²: 0.4743 | Mean Uncertainty: 1.3854

--- Kernel: matern_15 | LR: 0.01 | Noise: learned ---
   Noise: learned (GPyTorch default, trainable)


MSE: 1.7142 | R²: 0.4801 | Mean Uncertainty: 1.4070

--- Kernel: matern_15 | LR: 0.01 | Noise: 0.01 ---
   Noise init: 0.01 (trainable)


MSE: 1.7128 | R²: 0.4805 | Mean Uncertainty: 1.3792

--- Kernel: matern_15 | LR: 0.01 | Noise: 0.05 ---
   Noise init: 0.05 (trainable)


MSE: 1.7134 | R²: 0.4804 | Mean Uncertainty: 1.3813

--- Kernel: matern_15 | LR: 0.01 | Noise: 0.1 ---
   Noise init: 0.1 (trainable)


MSE: 1.7175 | R²: 0.4791 | Mean Uncertainty: 1.3819

--- Kernel: matern_15 | LR: 0.01 | Noise: 0.2 ---
   Noise init: 0.2 (trainable)


MSE: 1.7168 | R²: 0.4793 | Mean Uncertainty: 1.3855

--- Kernel: matern_15 | LR: 0.001 | Noise: learned ---
   Noise: learned (GPyTorch default, trainable)


MSE: 2.2694 | R²: 0.3117 | Mean Uncertainty: 1.7616

--- Kernel: matern_15 | LR: 0.001 | Noise: 0.01 ---
   Noise init: 0.01 (trainable)


MSE: 1.9856 | R²: 0.3978 | Mean Uncertainty: 1.4913

--- Kernel: matern_15 | LR: 0.001 | Noise: 0.05 ---
   Noise init: 0.05 (trainable)


MSE: 1.9951 | R²: 0.3949 | Mean Uncertainty: 1.5122

--- Kernel: matern_15 | LR: 0.001 | Noise: 0.1 ---
   Noise init: 0.1 (trainable)


MSE: 2.0083 | R²: 0.3909 | Mean Uncertainty: 1.5293

--- Kernel: matern_15 | LR: 0.001 | Noise: 0.2 ---
   Noise init: 0.2 (trainable)


MSE: 2.0405 | R²: 0.3812 | Mean Uncertainty: 1.5625

--- Kernel: matern_25 | LR: 0.05 | Noise: learned ---
   Noise: learned (GPyTorch default, trainable)


MSE: 1.7268 | R²: 0.4763 | Mean Uncertainty: 1.4091

--- Kernel: matern_25 | LR: 0.05 | Noise: 0.01 ---
   Noise init: 0.01 (trainable)


MSE: 1.7217 | R²: 0.4779 | Mean Uncertainty: 1.4045

--- Kernel: matern_25 | LR: 0.05 | Noise: 0.05 ---
   Noise init: 0.05 (trainable)


MSE: 1.7305 | R²: 0.4752 | Mean Uncertainty: 1.4022

--- Kernel: matern_25 | LR: 0.05 | Noise: 0.1 ---
   Noise init: 0.1 (trainable)


MSE: 1.7299 | R²: 0.4754 | Mean Uncertainty: 1.3967

--- Kernel: matern_25 | LR: 0.05 | Noise: 0.2 ---
   Noise init: 0.2 (trainable)


MSE: 1.7346 | R²: 0.4739 | Mean Uncertainty: 1.4056

--- Kernel: matern_25 | LR: 0.01 | Noise: learned ---
   Noise: learned (GPyTorch default, trainable)


MSE: 1.7119 | R²: 0.4808 | Mean Uncertainty: 1.4189

--- Kernel: matern_25 | LR: 0.01 | Noise: 0.01 ---
   Noise init: 0.01 (trainable)


MSE: 1.7184 | R²: 0.4788 | Mean Uncertainty: 1.3957

--- Kernel: matern_25 | LR: 0.01 | Noise: 0.05 ---
   Noise init: 0.05 (trainable)


MSE: 1.7216 | R²: 0.4779 | Mean Uncertainty: 1.3984

--- Kernel: matern_25 | LR: 0.01 | Noise: 0.1 ---
   Noise init: 0.1 (trainable)


MSE: 1.7143 | R²: 0.4801 | Mean Uncertainty: 1.3996

--- Kernel: matern_25 | LR: 0.01 | Noise: 0.2 ---
   Noise init: 0.2 (trainable)


MSE: 1.7174 | R²: 0.4792 | Mean Uncertainty: 1.4014

--- Kernel: matern_25 | LR: 0.001 | Noise: learned ---
   Noise: learned (GPyTorch default, trainable)


MSE: 2.2595 | R²: 0.3148 | Mean Uncertainty: 1.7606

--- Kernel: matern_25 | LR: 0.001 | Noise: 0.01 ---
   Noise init: 0.01 (trainable)


MSE: 1.9778 | R²: 0.4002 | Mean Uncertainty: 1.4893

--- Kernel: matern_25 | LR: 0.001 | Noise: 0.05 ---
   Noise init: 0.05 (trainable)


MSE: 1.9873 | R²: 0.3973 | Mean Uncertainty: 1.5110

--- Kernel: matern_25 | LR: 0.001 | Noise: 0.1 ---
   Noise init: 0.1 (trainable)


MSE: 2.0001 | R²: 0.3934 | Mean Uncertainty: 1.5285

--- Kernel: matern_25 | LR: 0.001 | Noise: 0.2 ---
   Noise init: 0.2 (trainable)


MSE: 2.0314 | R²: 0.3839 | Mean Uncertainty: 1.5624

--- Kernel: rbf_ard | LR: 0.05 | Noise: learned ---
   Noise: learned (GPyTorch default, trainable)


MSE: 1.7201 | R²: 0.4783 | Mean Uncertainty: 1.4640

--- Kernel: rbf_ard | LR: 0.05 | Noise: 0.01 ---
   Noise init: 0.01 (trainable)


MSE: 1.7214 | R²: 0.4779 | Mean Uncertainty: 1.4600

--- Kernel: rbf_ard | LR: 0.05 | Noise: 0.05 ---
   Noise init: 0.05 (trainable)


MSE: 1.7236 | R²: 0.4773 | Mean Uncertainty: 1.4597

--- Kernel: rbf_ard | LR: 0.05 | Noise: 0.1 ---
   Noise init: 0.1 (trainable)


MSE: 1.7223 | R²: 0.4777 | Mean Uncertainty: 1.4658

--- Kernel: rbf_ard | LR: 0.05 | Noise: 0.2 ---
   Noise init: 0.2 (trainable)


MSE: 1.7194 | R²: 0.4785 | Mean Uncertainty: 1.4713

--- Kernel: rbf_ard | LR: 0.01 | Noise: learned ---
   Noise: learned (GPyTorch default, trainable)


MSE: 1.6973 | R²: 0.4852 | Mean Uncertainty: 1.4572

--- Kernel: rbf_ard | LR: 0.01 | Noise: 0.01 ---
   Noise init: 0.01 (trainable)


MSE: 1.7122 | R²: 0.4807 | Mean Uncertainty: 1.4518

--- Kernel: rbf_ard | LR: 0.01 | Noise: 0.05 ---
   Noise init: 0.05 (trainable)


MSE: 1.7055 | R²: 0.4828 | Mean Uncertainty: 1.4402

--- Kernel: rbf_ard | LR: 0.01 | Noise: 0.1 ---
   Noise init: 0.1 (trainable)


MSE: 1.7064 | R²: 0.4825 | Mean Uncertainty: 1.4390

--- Kernel: rbf_ard | LR: 0.01 | Noise: 0.2 ---
   Noise init: 0.2 (trainable)


MSE: 1.6949 | R²: 0.4860 | Mean Uncertainty: 1.4408

--- Kernel: rbf_ard | LR: 0.001 | Noise: learned ---
   Noise: learned (GPyTorch default, trainable)


MSE: 2.2483 | R²: 0.3181 | Mean Uncertainty: 1.7591

--- Kernel: rbf_ard | LR: 0.001 | Noise: 0.01 ---
   Noise init: 0.01 (trainable)


MSE: 1.9671 | R²: 0.4034 | Mean Uncertainty: 1.4862

--- Kernel: rbf_ard | LR: 0.001 | Noise: 0.05 ---
   Noise init: 0.05 (trainable)


MSE: 1.9767 | R²: 0.4005 | Mean Uncertainty: 1.5104

--- Kernel: rbf_ard | LR: 0.001 | Noise: 0.1 ---
   Noise init: 0.1 (trainable)


MSE: 1.9916 | R²: 0.3960 | Mean Uncertainty: 1.5294

--- Kernel: rbf_ard | LR: 0.001 | Noise: 0.2 ---
   Noise init: 0.2 (trainable)


MSE: 2.0216 | R²: 0.3869 | Mean Uncertainty: 1.5635

 PCA = 15 components

--- Kernel: matern_15 | LR: 0.05 | Noise: learned ---
   Noise: learned (GPyTorch default, trainable)


MSE: 1.2817 | R²: 0.6113 | Mean Uncertainty: 1.3291

--- Kernel: matern_15 | LR: 0.05 | Noise: 0.01 ---
   Noise init: 0.01 (trainable)


MSE: 1.2669 | R²: 0.6158 | Mean Uncertainty: 1.3294

--- Kernel: matern_15 | LR: 0.05 | Noise: 0.05 ---
   Noise init: 0.05 (trainable)


MSE: 1.2697 | R²: 0.6149 | Mean Uncertainty: 1.3290

--- Kernel: matern_15 | LR: 0.05 | Noise: 0.1 ---
   Noise init: 0.1 (trainable)


MSE: 1.2701 | R²: 0.6148 | Mean Uncertainty: 1.3236

--- Kernel: matern_15 | LR: 0.05 | Noise: 0.2 ---
   Noise init: 0.2 (trainable)


MSE: 1.2732 | R²: 0.6139 | Mean Uncertainty: 1.3231

--- Kernel: matern_15 | LR: 0.01 | Noise: learned ---
   Noise: learned (GPyTorch default, trainable)


MSE: 1.2546 | R²: 0.6195 | Mean Uncertainty: 1.3373

--- Kernel: matern_15 | LR: 0.01 | Noise: 0.01 ---
   Noise init: 0.01 (trainable)


MSE: 1.2634 | R²: 0.6168 | Mean Uncertainty: 1.3079

--- Kernel: matern_15 | LR: 0.01 | Noise: 0.05 ---
   Noise init: 0.05 (trainable)


MSE: 1.2618 | R²: 0.6173 | Mean Uncertainty: 1.3083

--- Kernel: matern_15 | LR: 0.01 | Noise: 0.1 ---
   Noise init: 0.1 (trainable)


MSE: 1.2616 | R²: 0.6174 | Mean Uncertainty: 1.3089

--- Kernel: matern_15 | LR: 0.01 | Noise: 0.2 ---
   Noise init: 0.2 (trainable)


MSE: 1.2557 | R²: 0.6192 | Mean Uncertainty: 1.3134

--- Kernel: matern_15 | LR: 0.001 | Noise: learned ---
   Noise: learned (GPyTorch default, trainable)


MSE: 2.2839 | R²: 0.3073 | Mean Uncertainty: 1.7668

--- Kernel: matern_15 | LR: 0.001 | Noise: 0.01 ---
   Noise init: 0.01 (trainable)


MSE: 1.9736 | R²: 0.4015 | Mean Uncertainty: 1.5052

--- Kernel: matern_15 | LR: 0.001 | Noise: 0.05 ---
   Noise init: 0.05 (trainable)


MSE: 1.9839 | R²: 0.3983 | Mean Uncertainty: 1.5246

--- Kernel: matern_15 | LR: 0.001 | Noise: 0.1 ---
   Noise init: 0.1 (trainable)


MSE: 1.9980 | R²: 0.3940 | Mean Uncertainty: 1.5406

--- Kernel: matern_15 | LR: 0.001 | Noise: 0.2 ---
   Noise init: 0.2 (trainable)


MSE: 2.0331 | R²: 0.3834 | Mean Uncertainty: 1.5722

--- Kernel: matern_25 | LR: 0.05 | Noise: learned ---
   Noise: learned (GPyTorch default, trainable)


MSE: 1.3302 | R²: 0.5966 | Mean Uncertainty: 1.3519

--- Kernel: matern_25 | LR: 0.05 | Noise: 0.01 ---
   Noise init: 0.01 (trainable)


MSE: 1.3131 | R²: 0.6018 | Mean Uncertainty: 1.3621

--- Kernel: matern_25 | LR: 0.05 | Noise: 0.05 ---
   Noise init: 0.05 (trainable)


MSE: 1.3124 | R²: 0.6020 | Mean Uncertainty: 1.3577

--- Kernel: matern_25 | LR: 0.05 | Noise: 0.1 ---
   Noise init: 0.1 (trainable)


MSE: 1.3154 | R²: 0.6011 | Mean Uncertainty: 1.3469

--- Kernel: matern_25 | LR: 0.05 | Noise: 0.2 ---
   Noise init: 0.2 (trainable)


MSE: 1.3140 | R²: 0.6015 | Mean Uncertainty: 1.3464

--- Kernel: matern_25 | LR: 0.01 | Noise: learned ---
   Noise: learned (GPyTorch default, trainable)


MSE: 1.2561 | R²: 0.6191 | Mean Uncertainty: 1.3413

--- Kernel: matern_25 | LR: 0.01 | Noise: 0.01 ---
   Noise init: 0.01 (trainable)


MSE: 1.2678 | R²: 0.6155 | Mean Uncertainty: 1.3206

--- Kernel: matern_25 | LR: 0.01 | Noise: 0.05 ---
   Noise init: 0.05 (trainable)


MSE: 1.2660 | R²: 0.6161 | Mean Uncertainty: 1.3203

--- Kernel: matern_25 | LR: 0.01 | Noise: 0.1 ---
   Noise init: 0.1 (trainable)


MSE: 1.2555 | R²: 0.6192 | Mean Uncertainty: 1.3213

--- Kernel: matern_25 | LR: 0.01 | Noise: 0.2 ---
   Noise init: 0.2 (trainable)


MSE: 1.2540 | R²: 0.6197 | Mean Uncertainty: 1.3248

--- Kernel: matern_25 | LR: 0.001 | Noise: learned ---
   Noise: learned (GPyTorch default, trainable)


MSE: 2.2810 | R²: 0.3082 | Mean Uncertainty: 1.7659

--- Kernel: matern_25 | LR: 0.001 | Noise: 0.01 ---
   Noise init: 0.01 (trainable)


MSE: 1.9764 | R²: 0.4006 | Mean Uncertainty: 1.5027

--- Kernel: matern_25 | LR: 0.001 | Noise: 0.05 ---
   Noise init: 0.05 (trainable)


MSE: 1.9859 | R²: 0.3977 | Mean Uncertainty: 1.5235

--- Kernel: matern_25 | LR: 0.001 | Noise: 0.1 ---
   Noise init: 0.1 (trainable)


MSE: 1.9994 | R²: 0.3936 | Mean Uncertainty: 1.5406

--- Kernel: matern_25 | LR: 0.001 | Noise: 0.2 ---
   Noise init: 0.2 (trainable)


MSE: 2.0331 | R²: 0.3834 | Mean Uncertainty: 1.5726

--- Kernel: rbf_ard | LR: 0.05 | Noise: learned ---
   Noise: learned (GPyTorch default, trainable)


MSE: 1.4381 | R²: 0.5639 | Mean Uncertainty: 1.3834

--- Kernel: rbf_ard | LR: 0.05 | Noise: 0.01 ---
   Noise init: 0.01 (trainable)


MSE: 1.4134 | R²: 0.5713 | Mean Uncertainty: 1.3812

--- Kernel: rbf_ard | LR: 0.05 | Noise: 0.05 ---
   Noise init: 0.05 (trainable)


MSE: 1.4223 | R²: 0.5686 | Mean Uncertainty: 1.3814

--- Kernel: rbf_ard | LR: 0.05 | Noise: 0.1 ---
   Noise init: 0.1 (trainable)


MSE: 1.4264 | R²: 0.5674 | Mean Uncertainty: 1.3910

--- Kernel: rbf_ard | LR: 0.05 | Noise: 0.2 ---
   Noise init: 0.2 (trainable)


MSE: 1.4322 | R²: 0.5657 | Mean Uncertainty: 1.3941

--- Kernel: rbf_ard | LR: 0.01 | Noise: learned ---
   Noise: learned (GPyTorch default, trainable)


MSE: 1.3069 | R²: 0.6036 | Mean Uncertainty: 1.3724

--- Kernel: rbf_ard | LR: 0.01 | Noise: 0.01 ---
   Noise init: 0.01 (trainable)


MSE: 1.3379 | R²: 0.5943 | Mean Uncertainty: 1.3749

--- Kernel: rbf_ard | LR: 0.01 | Noise: 0.05 ---
   Noise init: 0.05 (trainable)


MSE: 1.3108 | R²: 0.6025 | Mean Uncertainty: 1.3656

--- Kernel: rbf_ard | LR: 0.01 | Noise: 0.1 ---
   Noise init: 0.1 (trainable)


MSE: 1.3130 | R²: 0.6018 | Mean Uncertainty: 1.3647

--- Kernel: rbf_ard | LR: 0.01 | Noise: 0.2 ---
   Noise init: 0.2 (trainable)


MSE: 1.3035 | R²: 0.6047 | Mean Uncertainty: 1.3580

--- Kernel: rbf_ard | LR: 0.001 | Noise: learned ---
   Noise: learned (GPyTorch default, trainable)


MSE: 2.2869 | R²: 0.3064 | Mean Uncertainty: 1.7640

--- Kernel: rbf_ard | LR: 0.001 | Noise: 0.01 ---
   Noise init: 0.01 (trainable)


MSE: 1.9928 | R²: 0.3956 | Mean Uncertainty: 1.4953

--- Kernel: rbf_ard | LR: 0.001 | Noise: 0.05 ---
   Noise init: 0.05 (trainable)


MSE: 2.0032 | R²: 0.3925 | Mean Uncertainty: 1.5209

--- Kernel: rbf_ard | LR: 0.001 | Noise: 0.1 ---
   Noise init: 0.1 (trainable)


MSE: 2.0153 | R²: 0.3888 | Mean Uncertainty: 1.5394

--- Kernel: rbf_ard | LR: 0.001 | Noise: 0.2 ---
   Noise init: 0.2 (trainable)


MSE: 2.0466 | R²: 0.3793 | Mean Uncertainty: 1.5723

 PCA = 20 components

--- Kernel: matern_15 | LR: 0.05 | Noise: learned ---
   Noise: learned (GPyTorch default, trainable)


MSE: 1.2159 | R²: 0.6313 | Mean Uncertainty: 1.3183

--- Kernel: matern_15 | LR: 0.05 | Noise: 0.01 ---
   Noise init: 0.01 (trainable)


MSE: 1.2119 | R²: 0.6324 | Mean Uncertainty: 1.3358

--- Kernel: matern_15 | LR: 0.05 | Noise: 0.05 ---
   Noise init: 0.05 (trainable)


MSE: 1.2144 | R²: 0.6317 | Mean Uncertainty: 1.3259

--- Kernel: matern_15 | LR: 0.05 | Noise: 0.1 ---
   Noise init: 0.1 (trainable)


MSE: 1.2172 | R²: 0.6308 | Mean Uncertainty: 1.3228

--- Kernel: matern_15 | LR: 0.05 | Noise: 0.2 ---
   Noise init: 0.2 (trainable)


MSE: 1.2148 | R²: 0.6316 | Mean Uncertainty: 1.3149

--- Kernel: matern_15 | LR: 0.01 | Noise: learned ---
   Noise: learned (GPyTorch default, trainable)


MSE: 1.1976 | R²: 0.6368 | Mean Uncertainty: 1.3191

--- Kernel: matern_15 | LR: 0.01 | Noise: 0.01 ---
   Noise init: 0.01 (trainable)


MSE: 1.2075 | R²: 0.6338 | Mean Uncertainty: 1.2869

--- Kernel: matern_15 | LR: 0.01 | Noise: 0.05 ---
   Noise init: 0.05 (trainable)


MSE: 1.2047 | R²: 0.6346 | Mean Uncertainty: 1.2898

--- Kernel: matern_15 | LR: 0.01 | Noise: 0.1 ---
   Noise init: 0.1 (trainable)


MSE: 1.2060 | R²: 0.6342 | Mean Uncertainty: 1.2912

--- Kernel: matern_15 | LR: 0.01 | Noise: 0.2 ---
   Noise init: 0.2 (trainable)


MSE: 1.1993 | R²: 0.6363 | Mean Uncertainty: 1.2950

--- Kernel: matern_15 | LR: 0.001 | Noise: learned ---
   Noise: learned (GPyTorch default, trainable)


MSE: 2.3008 | R²: 0.3022 | Mean Uncertainty: 1.7675

--- Kernel: matern_15 | LR: 0.001 | Noise: 0.01 ---
   Noise init: 0.01 (trainable)


MSE: 1.9892 | R²: 0.3967 | Mean Uncertainty: 1.5088

--- Kernel: matern_15 | LR: 0.001 | Noise: 0.05 ---
   Noise init: 0.05 (trainable)


MSE: 1.9994 | R²: 0.3936 | Mean Uncertainty: 1.5283

--- Kernel: matern_15 | LR: 0.001 | Noise: 0.1 ---
   Noise init: 0.1 (trainable)


MSE: 2.0135 | R²: 0.3893 | Mean Uncertainty: 1.5439

--- Kernel: matern_15 | LR: 0.001 | Noise: 0.2 ---
   Noise init: 0.2 (trainable)


MSE: 2.0486 | R²: 0.3787 | Mean Uncertainty: 1.5744

--- Kernel: matern_25 | LR: 0.05 | Noise: learned ---
   Noise: learned (GPyTorch default, trainable)


MSE: 1.2245 | R²: 0.6286 | Mean Uncertainty: 1.3366

--- Kernel: matern_25 | LR: 0.05 | Noise: 0.01 ---
   Noise init: 0.01 (trainable)


MSE: 1.2026 | R²: 0.6353 | Mean Uncertainty: 1.3523

--- Kernel: matern_25 | LR: 0.05 | Noise: 0.05 ---
   Noise init: 0.05 (trainable)


MSE: 1.2144 | R²: 0.6317 | Mean Uncertainty: 1.3502

--- Kernel: matern_25 | LR: 0.05 | Noise: 0.1 ---
   Noise init: 0.1 (trainable)


MSE: 1.2105 | R²: 0.6329 | Mean Uncertainty: 1.3552

--- Kernel: matern_25 | LR: 0.05 | Noise: 0.2 ---
   Noise init: 0.2 (trainable)


MSE: 1.2199 | R²: 0.6300 | Mean Uncertainty: 1.3498

--- Kernel: matern_25 | LR: 0.01 | Noise: learned ---
   Noise: learned (GPyTorch default, trainable)


MSE: 1.1829 | R²: 0.6413 | Mean Uncertainty: 1.3274

--- Kernel: matern_25 | LR: 0.01 | Noise: 0.01 ---
   Noise init: 0.01 (trainable)


MSE: 1.2001 | R²: 0.6360 | Mean Uncertainty: 1.3028

--- Kernel: matern_25 | LR: 0.01 | Noise: 0.05 ---
   Noise init: 0.05 (trainable)


MSE: 1.1948 | R²: 0.6377 | Mean Uncertainty: 1.3018

--- Kernel: matern_25 | LR: 0.01 | Noise: 0.1 ---
   Noise init: 0.1 (trainable)


MSE: 1.1959 | R²: 0.6373 | Mean Uncertainty: 1.3048

--- Kernel: matern_25 | LR: 0.01 | Noise: 0.2 ---
   Noise init: 0.2 (trainable)


MSE: 1.1911 | R²: 0.6388 | Mean Uncertainty: 1.3031

--- Kernel: matern_25 | LR: 0.001 | Noise: learned ---
   Noise: learned (GPyTorch default, trainable)


MSE: 2.2986 | R²: 0.3029 | Mean Uncertainty: 1.7674

--- Kernel: matern_25 | LR: 0.001 | Noise: 0.01 ---
   Noise init: 0.01 (trainable)


MSE: 1.9932 | R²: 0.3955 | Mean Uncertainty: 1.5073

--- Kernel: matern_25 | LR: 0.001 | Noise: 0.05 ---
   Noise init: 0.05 (trainable)


MSE: 2.0028 | R²: 0.3926 | Mean Uncertainty: 1.5290

--- Kernel: matern_25 | LR: 0.001 | Noise: 0.1 ---
   Noise init: 0.1 (trainable)


MSE: 2.0163 | R²: 0.3885 | Mean Uncertainty: 1.5457

--- Kernel: matern_25 | LR: 0.001 | Noise: 0.2 ---
   Noise init: 0.2 (trainable)


MSE: 2.0499 | R²: 0.3783 | Mean Uncertainty: 1.5767

--- Kernel: rbf_ard | LR: 0.05 | Noise: learned ---
   Noise: learned (GPyTorch default, trainable)


MSE: 1.2671 | R²: 0.6157 | Mean Uncertainty: 1.3468

--- Kernel: rbf_ard | LR: 0.05 | Noise: 0.01 ---
   Noise init: 0.01 (trainable)


MSE: 1.2565 | R²: 0.6189 | Mean Uncertainty: 1.3583

--- Kernel: rbf_ard | LR: 0.05 | Noise: 0.05 ---
   Noise init: 0.05 (trainable)


MSE: 1.2577 | R²: 0.6186 | Mean Uncertainty: 1.3578

--- Kernel: rbf_ard | LR: 0.05 | Noise: 0.1 ---
   Noise init: 0.1 (trainable)


MSE: 1.2554 | R²: 0.6193 | Mean Uncertainty: 1.3575

--- Kernel: rbf_ard | LR: 0.05 | Noise: 0.2 ---
   Noise init: 0.2 (trainable)


MSE: 1.2672 | R²: 0.6157 | Mean Uncertainty: 1.3563

--- Kernel: rbf_ard | LR: 0.01 | Noise: learned ---
   Noise: learned (GPyTorch default, trainable)


MSE: 1.1927 | R²: 0.6383 | Mean Uncertainty: 1.3472

--- Kernel: rbf_ard | LR: 0.01 | Noise: 0.01 ---
   Noise init: 0.01 (trainable)


MSE: 1.2216 | R²: 0.6295 | Mean Uncertainty: 1.3436

--- Kernel: rbf_ard | LR: 0.01 | Noise: 0.05 ---
   Noise init: 0.05 (trainable)


MSE: 1.2155 | R²: 0.6314 | Mean Uncertainty: 1.3391

--- Kernel: rbf_ard | LR: 0.01 | Noise: 0.1 ---
   Noise init: 0.1 (trainable)


MSE: 1.2158 | R²: 0.6313 | Mean Uncertainty: 1.3360

--- Kernel: rbf_ard | LR: 0.01 | Noise: 0.2 ---
   Noise init: 0.2 (trainable)


MSE: 1.2019 | R²: 0.6355 | Mean Uncertainty: 1.3215

--- Kernel: rbf_ard | LR: 0.001 | Noise: learned ---
   Noise: learned (GPyTorch default, trainable)


MSE: 2.3050 | R²: 0.3009 | Mean Uncertainty: 1.7641

--- Kernel: rbf_ard | LR: 0.001 | Noise: 0.01 ---
   Noise init: 0.01 (trainable)


MSE: 2.0122 | R²: 0.3897 | Mean Uncertainty: 1.5016

--- Kernel: rbf_ard | LR: 0.001 | Noise: 0.05 ---
   Noise init: 0.05 (trainable)


MSE: 2.0220 | R²: 0.3868 | Mean Uncertainty: 1.5241

--- Kernel: rbf_ard | LR: 0.001 | Noise: 0.1 ---
   Noise init: 0.1 (trainable)


MSE: 2.0342 | R²: 0.3831 | Mean Uncertainty: 1.5419

--- Kernel: rbf_ard | LR: 0.001 | Noise: 0.2 ---
   Noise init: 0.2 (trainable)


MSE: 2.0652 | R²: 0.3737 | Mean Uncertainty: 1.5737

 PCA = 30 components

--- Kernel: matern_15 | LR: 0.05 | Noise: learned ---
   Noise: learned (GPyTorch default, trainable)


MSE: 1.1408 | R²: 0.6540 | Mean Uncertainty: 1.2953

--- Kernel: matern_15 | LR: 0.05 | Noise: 0.01 ---
   Noise init: 0.01 (trainable)


MSE: 1.1320 | R²: 0.6567 | Mean Uncertainty: 1.2897

--- Kernel: matern_15 | LR: 0.05 | Noise: 0.05 ---
   Noise init: 0.05 (trainable)


MSE: 1.1407 | R²: 0.6541 | Mean Uncertainty: 1.2968

--- Kernel: matern_15 | LR: 0.05 | Noise: 0.1 ---
   Noise init: 0.1 (trainable)


MSE: 1.1395 | R²: 0.6544 | Mean Uncertainty: 1.2887

--- Kernel: matern_15 | LR: 0.05 | Noise: 0.2 ---
   Noise init: 0.2 (trainable)


MSE: 1.1407 | R²: 0.6541 | Mean Uncertainty: 1.2821

--- Kernel: matern_15 | LR: 0.01 | Noise: learned ---
   Noise: learned (GPyTorch default, trainable)


MSE: 1.1655 | R²: 0.6465 | Mean Uncertainty: 1.2901

--- Kernel: matern_15 | LR: 0.01 | Noise: 0.01 ---
   Noise init: 0.01 (trainable)


MSE: 1.1806 | R²: 0.6419 | Mean Uncertainty: 1.2601

--- Kernel: matern_15 | LR: 0.01 | Noise: 0.05 ---
   Noise init: 0.05 (trainable)


MSE: 1.1781 | R²: 0.6427 | Mean Uncertainty: 1.2610

--- Kernel: matern_15 | LR: 0.01 | Noise: 0.1 ---
   Noise init: 0.1 (trainable)


MSE: 1.1770 | R²: 0.6431 | Mean Uncertainty: 1.2608

--- Kernel: matern_15 | LR: 0.01 | Noise: 0.2 ---
   Noise init: 0.2 (trainable)


MSE: 1.1690 | R²: 0.6455 | Mean Uncertainty: 1.2655

--- Kernel: matern_15 | LR: 0.001 | Noise: learned ---
   Noise: learned (GPyTorch default, trainable)


MSE: 2.3168 | R²: 0.2974 | Mean Uncertainty: 1.7679

--- Kernel: matern_15 | LR: 0.001 | Noise: 0.01 ---
   Noise init: 0.01 (trainable)


MSE: 2.0080 | R²: 0.3910 | Mean Uncertainty: 1.5130

--- Kernel: matern_15 | LR: 0.001 | Noise: 0.05 ---
   Noise init: 0.05 (trainable)


MSE: 2.0181 | R²: 0.3880 | Mean Uncertainty: 1.5318

--- Kernel: matern_15 | LR: 0.001 | Noise: 0.1 ---
   Noise init: 0.1 (trainable)


MSE: 2.0319 | R²: 0.3838 | Mean Uncertainty: 1.5473

--- Kernel: matern_15 | LR: 0.001 | Noise: 0.2 ---
   Noise init: 0.2 (trainable)


MSE: 2.0665 | R²: 0.3733 | Mean Uncertainty: 1.5773

--- Kernel: matern_25 | LR: 0.05 | Noise: learned ---
   Noise: learned (GPyTorch default, trainable)


MSE: 1.1426 | R²: 0.6535 | Mean Uncertainty: 1.3114

--- Kernel: matern_25 | LR: 0.05 | Noise: 0.01 ---
   Noise init: 0.01 (trainable)


MSE: 1.1309 | R²: 0.6570 | Mean Uncertainty: 1.3173

--- Kernel: matern_25 | LR: 0.05 | Noise: 0.05 ---
   Noise init: 0.05 (trainable)


MSE: 1.1337 | R²: 0.6562 | Mean Uncertainty: 1.3149

--- Kernel: matern_25 | LR: 0.05 | Noise: 0.1 ---
   Noise init: 0.1 (trainable)


MSE: 1.1335 | R²: 0.6562 | Mean Uncertainty: 1.3083

--- Kernel: matern_25 | LR: 0.05 | Noise: 0.2 ---
   Noise init: 0.2 (trainable)


MSE: 1.1304 | R²: 0.6572 | Mean Uncertainty: 1.3116

--- Kernel: matern_25 | LR: 0.01 | Noise: learned ---
   Noise: learned (GPyTorch default, trainable)


MSE: 1.1483 | R²: 0.6518 | Mean Uncertainty: 1.2934

--- Kernel: matern_25 | LR: 0.01 | Noise: 0.01 ---
   Noise init: 0.01 (trainable)


MSE: 1.1697 | R²: 0.6453 | Mean Uncertainty: 1.2694

--- Kernel: matern_25 | LR: 0.01 | Noise: 0.05 ---
   Noise init: 0.05 (trainable)


MSE: 1.1580 | R²: 0.6488 | Mean Uncertainty: 1.2652

--- Kernel: matern_25 | LR: 0.01 | Noise: 0.1 ---
   Noise init: 0.1 (trainable)


MSE: 1.1587 | R²: 0.6486 | Mean Uncertainty: 1.2660

--- Kernel: matern_25 | LR: 0.01 | Noise: 0.2 ---
   Noise init: 0.2 (trainable)


MSE: 1.1543 | R²: 0.6499 | Mean Uncertainty: 1.2683

--- Kernel: matern_25 | LR: 0.001 | Noise: learned ---
   Noise: learned (GPyTorch default, trainable)


MSE: 2.3154 | R²: 0.2978 | Mean Uncertainty: 1.7680

--- Kernel: matern_25 | LR: 0.001 | Noise: 0.01 ---
   Noise init: 0.01 (trainable)


MSE: 2.0132 | R²: 0.3894 | Mean Uncertainty: 1.5106

--- Kernel: matern_25 | LR: 0.001 | Noise: 0.05 ---
   Noise init: 0.05 (trainable)


MSE: 2.0227 | R²: 0.3866 | Mean Uncertainty: 1.5314

--- Kernel: matern_25 | LR: 0.001 | Noise: 0.1 ---
   Noise init: 0.1 (trainable)


MSE: 2.0358 | R²: 0.3826 | Mean Uncertainty: 1.5477

--- Kernel: matern_25 | LR: 0.001 | Noise: 0.2 ---
   Noise init: 0.2 (trainable)


MSE: 2.0689 | R²: 0.3726 | Mean Uncertainty: 1.5785

--- Kernel: rbf_ard | LR: 0.05 | Noise: learned ---
   Noise: learned (GPyTorch default, trainable)


MSE: 1.1719 | R²: 0.6446 | Mean Uncertainty: 1.3220

--- Kernel: rbf_ard | LR: 0.05 | Noise: 0.01 ---
   Noise init: 0.01 (trainable)


MSE: 1.1898 | R²: 0.6392 | Mean Uncertainty: 1.3258

--- Kernel: rbf_ard | LR: 0.05 | Noise: 0.05 ---
   Noise init: 0.05 (trainable)


MSE: 1.1858 | R²: 0.6404 | Mean Uncertainty: 1.3303

--- Kernel: rbf_ard | LR: 0.05 | Noise: 0.1 ---
   Noise init: 0.1 (trainable)


MSE: 1.1820 | R²: 0.6415 | Mean Uncertainty: 1.3217

--- Kernel: rbf_ard | LR: 0.05 | Noise: 0.2 ---
   Noise init: 0.2 (trainable)


MSE: 1.1790 | R²: 0.6424 | Mean Uncertainty: 1.3304

--- Kernel: rbf_ard | LR: 0.01 | Noise: learned ---
   Noise: learned (GPyTorch default, trainable)


MSE: 1.1692 | R²: 0.6454 | Mean Uncertainty: 1.3097

--- Kernel: rbf_ard | LR: 0.01 | Noise: 0.01 ---
   Noise init: 0.01 (trainable)


MSE: 1.1978 | R²: 0.6367 | Mean Uncertainty: 1.3065

--- Kernel: rbf_ard | LR: 0.01 | Noise: 0.05 ---
   Noise init: 0.05 (trainable)


MSE: 1.1826 | R²: 0.6413 | Mean Uncertainty: 1.3017

--- Kernel: rbf_ard | LR: 0.01 | Noise: 0.1 ---
   Noise init: 0.1 (trainable)


MSE: 1.1830 | R²: 0.6412 | Mean Uncertainty: 1.2902

--- Kernel: rbf_ard | LR: 0.01 | Noise: 0.2 ---
   Noise init: 0.2 (trainable)


MSE: 1.1768 | R²: 0.6431 | Mean Uncertainty: 1.2955

--- Kernel: rbf_ard | LR: 0.001 | Noise: learned ---
   Noise: learned (GPyTorch default, trainable)


MSE: 2.3221 | R²: 0.2958 | Mean Uncertainty: 1.7650

--- Kernel: rbf_ard | LR: 0.001 | Noise: 0.01 ---
   Noise init: 0.01 (trainable)


MSE: 2.0334 | R²: 0.3833 | Mean Uncertainty: 1.5061

--- Kernel: rbf_ard | LR: 0.001 | Noise: 0.05 ---
   Noise init: 0.05 (trainable)


MSE: 2.0430 | R²: 0.3804 | Mean Uncertainty: 1.5279

--- Kernel: rbf_ard | LR: 0.001 | Noise: 0.1 ---
   Noise init: 0.1 (trainable)


MSE: 2.0549 | R²: 0.3768 | Mean Uncertainty: 1.5450

--- Kernel: rbf_ard | LR: 0.001 | Noise: 0.2 ---
   Noise init: 0.2 (trainable)


MSE: 2.0852 | R²: 0.3676 | Mean Uncertainty: 1.5761

 PCA = 40 components

--- Kernel: matern_15 | LR: 0.05 | Noise: learned ---
   Noise: learned (GPyTorch default, trainable)


MSE: 1.0299 | R²: 0.6877 | Mean Uncertainty: 1.2385

--- Kernel: matern_15 | LR: 0.05 | Noise: 0.01 ---
   Noise init: 0.01 (trainable)


MSE: 1.0434 | R²: 0.6836 | Mean Uncertainty: 1.2493

--- Kernel: matern_15 | LR: 0.05 | Noise: 0.05 ---
   Noise init: 0.05 (trainable)


MSE: 1.0488 | R²: 0.6819 | Mean Uncertainty: 1.2612

--- Kernel: matern_15 | LR: 0.05 | Noise: 0.1 ---
   Noise init: 0.1 (trainable)


MSE: 1.0266 | R²: 0.6886 | Mean Uncertainty: 1.2362

--- Kernel: matern_15 | LR: 0.05 | Noise: 0.2 ---
   Noise init: 0.2 (trainable)


MSE: 1.0395 | R²: 0.6847 | Mean Uncertainty: 1.2489

--- Kernel: matern_15 | LR: 0.01 | Noise: learned ---
   Noise: learned (GPyTorch default, trainable)


MSE: 1.1325 | R²: 0.6565 | Mean Uncertainty: 1.2663

--- Kernel: matern_15 | LR: 0.01 | Noise: 0.01 ---
   Noise init: 0.01 (trainable)


MSE: 1.1494 | R²: 0.6514 | Mean Uncertainty: 1.2362

--- Kernel: matern_15 | LR: 0.01 | Noise: 0.05 ---
   Noise init: 0.05 (trainable)


MSE: 1.1469 | R²: 0.6522 | Mean Uncertainty: 1.2352

--- Kernel: matern_15 | LR: 0.01 | Noise: 0.1 ---
   Noise init: 0.1 (trainable)


MSE: 1.1452 | R²: 0.6527 | Mean Uncertainty: 1.2370

--- Kernel: matern_15 | LR: 0.01 | Noise: 0.2 ---
   Noise init: 0.2 (trainable)


MSE: 1.1401 | R²: 0.6542 | Mean Uncertainty: 1.2425

--- Kernel: matern_15 | LR: 0.001 | Noise: learned ---
   Noise: learned (GPyTorch default, trainable)


MSE: 2.3210 | R²: 0.2961 | Mean Uncertainty: 1.7685

--- Kernel: matern_15 | LR: 0.001 | Noise: 0.01 ---
   Noise init: 0.01 (trainable)


MSE: 2.0127 | R²: 0.3896 | Mean Uncertainty: 1.5145

--- Kernel: matern_15 | LR: 0.001 | Noise: 0.05 ---
   Noise init: 0.05 (trainable)


MSE: 2.0228 | R²: 0.3865 | Mean Uncertainty: 1.5330

--- Kernel: matern_15 | LR: 0.001 | Noise: 0.1 ---
   Noise init: 0.1 (trainable)


MSE: 2.0366 | R²: 0.3823 | Mean Uncertainty: 1.5489

--- Kernel: matern_15 | LR: 0.001 | Noise: 0.2 ---
   Noise init: 0.2 (trainable)


MSE: 2.0711 | R²: 0.3719 | Mean Uncertainty: 1.5789

--- Kernel: matern_25 | LR: 0.05 | Noise: learned ---
   Noise: learned (GPyTorch default, trainable)


MSE: 1.0290 | R²: 0.6879 | Mean Uncertainty: 1.2730

--- Kernel: matern_25 | LR: 0.05 | Noise: 0.01 ---
   Noise init: 0.01 (trainable)


MSE: 1.0231 | R²: 0.6897 | Mean Uncertainty: 1.2755

--- Kernel: matern_25 | LR: 0.05 | Noise: 0.05 ---
   Noise init: 0.05 (trainable)


MSE: 1.0178 | R²: 0.6913 | Mean Uncertainty: 1.2706

--- Kernel: matern_25 | LR: 0.05 | Noise: 0.1 ---
   Noise init: 0.1 (trainable)


MSE: 1.0163 | R²: 0.6918 | Mean Uncertainty: 1.2778

--- Kernel: matern_25 | LR: 0.05 | Noise: 0.2 ---
   Noise init: 0.2 (trainable)


MSE: 1.0238 | R²: 0.6895 | Mean Uncertainty: 1.2733

--- Kernel: matern_25 | LR: 0.01 | Noise: learned ---
   Noise: learned (GPyTorch default, trainable)


MSE: 1.1235 | R²: 0.6593 | Mean Uncertainty: 1.2675

--- Kernel: matern_25 | LR: 0.01 | Noise: 0.01 ---
   Noise init: 0.01 (trainable)


MSE: 1.1540 | R²: 0.6500 | Mean Uncertainty: 1.2392

--- Kernel: matern_25 | LR: 0.01 | Noise: 0.05 ---
   Noise init: 0.05 (trainable)


MSE: 1.1443 | R²: 0.6530 | Mean Uncertainty: 1.2438

--- Kernel: matern_25 | LR: 0.01 | Noise: 0.1 ---
   Noise init: 0.1 (trainable)


MSE: 1.1371 | R²: 0.6552 | Mean Uncertainty: 1.2415

--- Kernel: matern_25 | LR: 0.01 | Noise: 0.2 ---
   Noise init: 0.2 (trainable)


MSE: 1.1296 | R²: 0.6574 | Mean Uncertainty: 1.2412

--- Kernel: matern_25 | LR: 0.001 | Noise: learned ---
   Noise: learned (GPyTorch default, trainable)


MSE: 2.3197 | R²: 0.2965 | Mean Uncertainty: 1.7681

--- Kernel: matern_25 | LR: 0.001 | Noise: 0.01 ---
   Noise init: 0.01 (trainable)


MSE: 2.0183 | R²: 0.3879 | Mean Uncertainty: 1.5108

--- Kernel: matern_25 | LR: 0.001 | Noise: 0.05 ---
   Noise init: 0.05 (trainable)


MSE: 2.0278 | R²: 0.3850 | Mean Uncertainty: 1.5315

--- Kernel: matern_25 | LR: 0.001 | Noise: 0.1 ---
   Noise init: 0.1 (trainable)


MSE: 2.0408 | R²: 0.3811 | Mean Uncertainty: 1.5479

--- Kernel: matern_25 | LR: 0.001 | Noise: 0.2 ---
   Noise init: 0.2 (trainable)


MSE: 2.0738 | R²: 0.3711 | Mean Uncertainty: 1.5787

--- Kernel: rbf_ard | LR: 0.05 | Noise: learned ---
   Noise: learned (GPyTorch default, trainable)


MSE: 1.0868 | R²: 0.6704 | Mean Uncertainty: 1.2929

--- Kernel: rbf_ard | LR: 0.05 | Noise: 0.01 ---
   Noise init: 0.01 (trainable)


MSE: 1.0846 | R²: 0.6711 | Mean Uncertainty: 1.2780

--- Kernel: rbf_ard | LR: 0.05 | Noise: 0.05 ---
   Noise init: 0.05 (trainable)


MSE: 1.0810 | R²: 0.6721 | Mean Uncertainty: 1.2947

--- Kernel: rbf_ard | LR: 0.05 | Noise: 0.1 ---
   Noise init: 0.1 (trainable)


MSE: 1.0785 | R²: 0.6729 | Mean Uncertainty: 1.2933

--- Kernel: rbf_ard | LR: 0.05 | Noise: 0.2 ---
   Noise init: 0.2 (trainable)


MSE: 1.0790 | R²: 0.6728 | Mean Uncertainty: 1.2987

--- Kernel: rbf_ard | LR: 0.01 | Noise: learned ---
   Noise: learned (GPyTorch default, trainable)


MSE: 1.1410 | R²: 0.6540 | Mean Uncertainty: 1.2699

--- Kernel: rbf_ard | LR: 0.01 | Noise: 0.01 ---
   Noise init: 0.01 (trainable)


MSE: 1.2027 | R²: 0.6352 | Mean Uncertainty: 1.2693

--- Kernel: rbf_ard | LR: 0.01 | Noise: 0.05 ---
   Noise init: 0.05 (trainable)


MSE: 1.1946 | R²: 0.6377 | Mean Uncertainty: 1.2724

--- Kernel: rbf_ard | LR: 0.01 | Noise: 0.1 ---
   Noise init: 0.1 (trainable)


MSE: 1.1762 | R²: 0.6433 | Mean Uncertainty: 1.2657

--- Kernel: rbf_ard | LR: 0.01 | Noise: 0.2 ---
   Noise init: 0.2 (trainable)


MSE: 1.1713 | R²: 0.6448 | Mean Uncertainty: 1.2546

--- Kernel: rbf_ard | LR: 0.001 | Noise: learned ---
   Noise: learned (GPyTorch default, trainable)


MSE: 2.3264 | R²: 0.2945 | Mean Uncertainty: 1.7652

--- Kernel: rbf_ard | LR: 0.001 | Noise: 0.01 ---
   Noise init: 0.01 (trainable)


MSE: 2.0388 | R²: 0.3817 | Mean Uncertainty: 1.5080

--- Kernel: rbf_ard | LR: 0.001 | Noise: 0.05 ---
   Noise init: 0.05 (trainable)


MSE: 2.0483 | R²: 0.3788 | Mean Uncertainty: 1.5298

--- Kernel: rbf_ard | LR: 0.001 | Noise: 0.1 ---
   Noise init: 0.1 (trainable)


MSE: 2.0601 | R²: 0.3752 | Mean Uncertainty: 1.5469

--- Kernel: rbf_ard | LR: 0.001 | Noise: 0.2 ---
   Noise init: 0.2 (trainable)


MSE: 2.0903 | R²: 0.3661 | Mean Uncertainty: 1.5773

 PCA = 50 components

--- Kernel: matern_15 | LR: 0.05 | Noise: learned ---
   Noise: learned (GPyTorch default, trainable)


MSE: 1.0886 | R²: 0.6699 | Mean Uncertainty: 1.2330

--- Kernel: matern_15 | LR: 0.05 | Noise: 0.01 ---
   Noise init: 0.01 (trainable)


MSE: 1.0906 | R²: 0.6693 | Mean Uncertainty: 1.2289

--- Kernel: matern_15 | LR: 0.05 | Noise: 0.05 ---
   Noise init: 0.05 (trainable)


MSE: 1.0995 | R²: 0.6665 | Mean Uncertainty: 1.2296

--- Kernel: matern_15 | LR: 0.05 | Noise: 0.1 ---
   Noise init: 0.1 (trainable)


MSE: 1.0960 | R²: 0.6676 | Mean Uncertainty: 1.2295

--- Kernel: matern_15 | LR: 0.05 | Noise: 0.2 ---
   Noise init: 0.2 (trainable)


MSE: 1.0911 | R²: 0.6691 | Mean Uncertainty: 1.2333

--- Kernel: matern_15 | LR: 0.01 | Noise: learned ---
   Noise: learned (GPyTorch default, trainable)


MSE: 1.1334 | R²: 0.6563 | Mean Uncertainty: 1.2491

--- Kernel: matern_15 | LR: 0.01 | Noise: 0.01 ---
   Noise init: 0.01 (trainable)


MSE: 1.1669 | R²: 0.6461 | Mean Uncertainty: 1.2198

--- Kernel: matern_15 | LR: 0.01 | Noise: 0.05 ---
   Noise init: 0.05 (trainable)


MSE: 1.1635 | R²: 0.6471 | Mean Uncertainty: 1.2213

--- Kernel: matern_15 | LR: 0.01 | Noise: 0.1 ---
   Noise init: 0.1 (trainable)


MSE: 1.1578 | R²: 0.6489 | Mean Uncertainty: 1.2242

--- Kernel: matern_15 | LR: 0.01 | Noise: 0.2 ---
   Noise init: 0.2 (trainable)


MSE: 1.1523 | R²: 0.6505 | Mean Uncertainty: 1.2232

--- Kernel: matern_15 | LR: 0.001 | Noise: learned ---
   Noise: learned (GPyTorch default, trainable)


MSE: 2.3225 | R²: 0.2957 | Mean Uncertainty: 1.7688

--- Kernel: matern_15 | LR: 0.001 | Noise: 0.01 ---
   Noise init: 0.01 (trainable)


MSE: 2.0143 | R²: 0.3891 | Mean Uncertainty: 1.5156

--- Kernel: matern_15 | LR: 0.001 | Noise: 0.05 ---
   Noise init: 0.05 (trainable)


MSE: 2.0244 | R²: 0.3861 | Mean Uncertainty: 1.5342

--- Kernel: matern_15 | LR: 0.001 | Noise: 0.1 ---
   Noise init: 0.1 (trainable)


MSE: 2.0382 | R²: 0.3819 | Mean Uncertainty: 1.5489

--- Kernel: matern_15 | LR: 0.001 | Noise: 0.2 ---
   Noise init: 0.2 (trainable)


MSE: 2.0726 | R²: 0.3714 | Mean Uncertainty: 1.5794

--- Kernel: matern_25 | LR: 0.05 | Noise: learned ---
   Noise: learned (GPyTorch default, trainable)


MSE: 1.1162 | R²: 0.6615 | Mean Uncertainty: 1.2570

--- Kernel: matern_25 | LR: 0.05 | Noise: 0.01 ---
   Noise init: 0.01 (trainable)


MSE: 1.1098 | R²: 0.6634 | Mean Uncertainty: 1.2588

--- Kernel: matern_25 | LR: 0.05 | Noise: 0.05 ---
   Noise init: 0.05 (trainable)


MSE: 1.1169 | R²: 0.6613 | Mean Uncertainty: 1.2632

--- Kernel: matern_25 | LR: 0.05 | Noise: 0.1 ---
   Noise init: 0.1 (trainable)


MSE: 1.1150 | R²: 0.6618 | Mean Uncertainty: 1.2598

--- Kernel: matern_25 | LR: 0.05 | Noise: 0.2 ---
   Noise init: 0.2 (trainable)


MSE: 1.1126 | R²: 0.6626 | Mean Uncertainty: 1.2640

--- Kernel: matern_25 | LR: 0.01 | Noise: learned ---
   Noise: learned (GPyTorch default, trainable)


MSE: 1.1263 | R²: 0.6584 | Mean Uncertainty: 1.2465

--- Kernel: matern_25 | LR: 0.01 | Noise: 0.01 ---
   Noise init: 0.01 (trainable)


MSE: 1.1668 | R²: 0.6461 | Mean Uncertainty: 1.2238

--- Kernel: matern_25 | LR: 0.01 | Noise: 0.05 ---
   Noise init: 0.05 (trainable)


MSE: 1.1612 | R²: 0.6478 | Mean Uncertainty: 1.2199

--- Kernel: matern_25 | LR: 0.01 | Noise: 0.1 ---
   Noise init: 0.1 (trainable)


MSE: 1.1546 | R²: 0.6498 | Mean Uncertainty: 1.2202

--- Kernel: matern_25 | LR: 0.01 | Noise: 0.2 ---
   Noise init: 0.2 (trainable)


MSE: 1.1499 | R²: 0.6513 | Mean Uncertainty: 1.2249

--- Kernel: matern_25 | LR: 0.001 | Noise: learned ---
   Noise: learned (GPyTorch default, trainable)


MSE: 2.3212 | R²: 0.2960 | Mean Uncertainty: 1.7682

--- Kernel: matern_25 | LR: 0.001 | Noise: 0.01 ---
   Noise init: 0.01 (trainable)


MSE: 2.0199 | R²: 0.3874 | Mean Uncertainty: 1.5105

--- Kernel: matern_25 | LR: 0.001 | Noise: 0.05 ---
   Noise init: 0.05 (trainable)


MSE: 2.0293 | R²: 0.3845 | Mean Uncertainty: 1.5316

--- Kernel: matern_25 | LR: 0.001 | Noise: 0.1 ---
   Noise init: 0.1 (trainable)


MSE: 2.0424 | R²: 0.3806 | Mean Uncertainty: 1.5479

--- Kernel: matern_25 | LR: 0.001 | Noise: 0.2 ---
   Noise init: 0.2 (trainable)


MSE: 2.0753 | R²: 0.3706 | Mean Uncertainty: 1.5787

--- Kernel: rbf_ard | LR: 0.05 | Noise: learned ---
   Noise: learned (GPyTorch default, trainable)


MSE: 1.1210 | R²: 0.6600 | Mean Uncertainty: 1.2867

--- Kernel: rbf_ard | LR: 0.05 | Noise: 0.01 ---
   Noise init: 0.01 (trainable)


MSE: 1.1623 | R²: 0.6475 | Mean Uncertainty: 1.2730

--- Kernel: rbf_ard | LR: 0.05 | Noise: 0.05 ---
   Noise init: 0.05 (trainable)


MSE: 1.1292 | R²: 0.6575 | Mean Uncertainty: 1.2805

--- Kernel: rbf_ard | LR: 0.05 | Noise: 0.1 ---
   Noise init: 0.1 (trainable)


MSE: 1.1361 | R²: 0.6554 | Mean Uncertainty: 1.2875

--- Kernel: rbf_ard | LR: 0.05 | Noise: 0.2 ---
   Noise init: 0.2 (trainable)


MSE: 1.1333 | R²: 0.6563 | Mean Uncertainty: 1.2954

--- Kernel: rbf_ard | LR: 0.01 | Noise: learned ---
   Noise: learned (GPyTorch default, trainable)


MSE: 1.1472 | R²: 0.6521 | Mean Uncertainty: 1.2522

--- Kernel: rbf_ard | LR: 0.01 | Noise: 0.01 ---
   Noise init: 0.01 (trainable)


MSE: 1.2111 | R²: 0.6327 | Mean Uncertainty: 1.2511

--- Kernel: rbf_ard | LR: 0.01 | Noise: 0.05 ---
   Noise init: 0.05 (trainable)


MSE: 1.2027 | R²: 0.6353 | Mean Uncertainty: 1.2491

--- Kernel: rbf_ard | LR: 0.01 | Noise: 0.1 ---
   Noise init: 0.1 (trainable)


MSE: 1.1888 | R²: 0.6395 | Mean Uncertainty: 1.2459

--- Kernel: rbf_ard | LR: 0.01 | Noise: 0.2 ---
   Noise init: 0.2 (trainable)


MSE: 1.1737 | R²: 0.6441 | Mean Uncertainty: 1.2352

--- Kernel: rbf_ard | LR: 0.001 | Noise: learned ---
   Noise: learned (GPyTorch default, trainable)


MSE: 2.3277 | R²: 0.2941 | Mean Uncertainty: 1.7651

--- Kernel: rbf_ard | LR: 0.001 | Noise: 0.01 ---
   Noise init: 0.01 (trainable)


MSE: 2.0404 | R²: 0.3812 | Mean Uncertainty: 1.5082

--- Kernel: rbf_ard | LR: 0.001 | Noise: 0.05 ---
   Noise init: 0.05 (trainable)


MSE: 2.0497 | R²: 0.3784 | Mean Uncertainty: 1.5302

--- Kernel: rbf_ard | LR: 0.001 | Noise: 0.1 ---
   Noise init: 0.1 (trainable)


MSE: 2.0615 | R²: 0.3748 | Mean Uncertainty: 1.5472

--- Kernel: rbf_ard | LR: 0.001 | Noise: 0.2 ---
   Noise init: 0.2 (trainable)


MSE: 2.0917 | R²: 0.3656 | Mean Uncertainty: 1.5775


In [7]:
# Build DataFrame containing all model results
df_results = pd.DataFrame(
    results,
    columns=["PCA", "Kernel", "LR", "Noise", "MSE", "R2", "Mean_Uncertainty", "UncertaintyDF"]
)

In [8]:
# Best model based on the higest $R^2$ and then lowest uncertainty
best_by_r2 = df_results.sort_values(
    ["R2", "Mean_Uncertainty"],
    ascending=[False, True]
).iloc[0]

print("\n===== BEST MODEL FOUND =====")
print(f"PCA components:   {best_by_r2['PCA']}")
print(f"Kernel:           {best_by_r2['Kernel']}")
print(f"Learning rate:    {best_by_r2['LR']}")
print(f"Noise setting:    {best_by_r2['Noise']}")
print(f"MSE:              {best_by_r2['MSE']:.4f}")
print(f"R²:               {best_by_r2['R2']:.4f}")
print(f"Mean uncertainty: {best_by_r2['Mean_Uncertainty']:.4f}")



===== BEST MODEL FOUND =====
PCA components:   40
Kernel:           matern_25
Learning rate:    0.05
Noise setting:    0.1
MSE:              1.0163
R²:               0.6918
Mean uncertainty: 1.2778


In [9]:
# Mean uncertainty per class based on the model with higest $R^2$ and then lowest uncertainty
df_unc_best = best_by_r2["UncertaintyDF"]

unc_by_class = df_unc_best.groupby("true")["std"].mean()

print("\n===== MEAN UNCERTAINTY (STD) PER ISUP CLASS =====")
for cls, std in unc_by_class.items():
    print(f"ISUP {cls}:  std = {std:.4f}")



===== MEAN UNCERTAINTY (STD) PER ISUP CLASS =====
ISUP 0:  std = 1.4363
ISUP 1:  std = 1.3873
ISUP 2:  std = 1.4076
ISUP 3:  std = 1.2335
ISUP 4:  std = 0.9228
ISUP 5:  std = 1.1140


In [ ]:
# Convert regression outputs of the best model into class labels 
# Compute classification metrics
# Model with the higest $R^2$ and then lowest uncertainty
y_true = df_unc_best["true"].values
y_pred = df_unc_best["pred"].values

# Round predictions (0–5)
y_pred_round = np.clip(np.round(y_pred), 0, 5).astype(int)

acc = accuracy_score(y_true, y_pred_round)
f1_macro = f1_score(y_true, y_pred_round, average="macro")
cm = confusion_matrix(y_true, y_pred_round)

print("\n ROUNDED METRICS FOR BEST MODEL")
print(f"Accuracy:   {acc:.4f}")
print(f"F1 Macro:   {f1_macro:.4f}")
print("Confusion Matrix:")
print(cm)



 ROUNDED METRICS FOR BEST MODEL
Accuracy:   0.4927
F1 Macro:   0.5306
Confusion Matrix:
[[10 34 14  3  0  0]
 [ 4 15  7  2  0  0]
 [ 1 15  9  1  2  0]
 [ 1  1  8 20  0  0]
 [ 0  0  2  0 27  0]
 [ 0  0  0  2  7 20]]


In [11]:
# Best model based on the lowest uncertainty and then higest $R^2$ 

best_by_unc = df_results.sort_values(
    ["Mean_Uncertainty", "R2"],
    ascending=[True, False]
).iloc[0]

print("\n===== BEST MODEL FOUND =====")
print(f"PCA components:   {best_by_unc['PCA']}")
print(f"Kernel:           {best_by_unc['Kernel']}")
print(f"Learning rate:    {best_by_unc['LR']}")
print(f"Noise setting:    {best_by_unc['Noise']}")
print(f"MSE:              {best_by_unc['MSE']:.4f}")
print(f"R²:               {best_by_unc['R2']:.4f}")
print(f"Mean uncertainty: {best_by_unc['Mean_Uncertainty']:.4f}")



===== BEST MODEL FOUND =====
PCA components:   50
Kernel:           matern_15
Learning rate:    0.01
Noise setting:    0.01
MSE:              1.1669
R²:               0.6461
Mean uncertainty: 1.2198


In [16]:
# Mean uncertainty per class based on the lowest uncertainty and then higest $R^2$
df_unc_best_un = best_by_unc["UncertaintyDF"]

unc_by_class_un = df_unc_best_un.groupby("true")["std"].mean()

print("\n===== MEAN UNCERTAINTY (STD) PER ISUP CLASS =====")
for cls, std in unc_by_class_un.items():
    print(f"ISUP {cls}:  std = {std:.4f}")



===== MEAN UNCERTAINTY (STD) PER ISUP CLASS =====
ISUP 0:  std = 1.3419
ISUP 1:  std = 1.3188
ISUP 2:  std = 1.3107
ISUP 3:  std = 1.2027
ISUP 4:  std = 0.9082
ISUP 5:  std = 1.1087


In [17]:
# Convert regression outputs of the best model into class labels 
# Compute classification metrics
# Model with the lowest uncertainty and the  highest $R^2$
y_true = df_unc_best_un["true"].values
y_pred = df_unc_best_un["pred"].values

# Round predictions (0–5)
y_pred_round = np.clip(np.round(y_pred), 0, 5).astype(int)

acc = accuracy_score(y_true, y_pred_round)
f1_macro = f1_score(y_true, y_pred_round, average="macro")
cm = confusion_matrix(y_true, y_pred_round)

print("\n ROUNDED METRICS FOR BEST MODEL")
print(f"Accuracy:   {acc:.4f}")
print(f"F1 Macro:   {f1_macro:.4f}")
print("Confusion Matrix:")
print(cm)



 ROUNDED METRICS FOR BEST MODEL
Accuracy:   0.4390
F1 Macro:   0.4765
Confusion Matrix:
[[ 5 36 18  2  0  0]
 [ 3 14  8  3  0  0]
 [ 2 12  9  4  1  0]
 [ 0  3  8 19  0  0]
 [ 0  0  1  3 25  0]
 [ 0  0  1  4  6 18]]
